---
- hosts: all
  gather_facts: true
  become: true
  vars:
    timezone: Europe/Paris

  tasks:
    - name: install packages
      ansible.builtin.package:
        state: present
        name:
          - tar
    - name: set as default locale
      ansible.builtin.command: localectl set-locale LANG=fr_FR.UTF-8
    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"
